export const analysisTypography = {
  caption: 'text-[12px] leading-4',
  bodySm: 'text-[14px] leading-5',
  body: 'text-[16px] leading-6',
  sectionTitle: 'text-[18px] leading-6 font-bold',
  kpiValue: 'text-[28px] md:text-[32px] leading-none font-black tabular-nums',
  sectionLabel: 'text-[12px] font-bold uppercase tracking-[0.14em]',
  cardTitle: 'text-[14px] font-bold text-[var(--color-text-primary)]',
  description: 'text-[14px] text-[var(--color-text-secondary)] leading-relaxed',
  label: 'text-[12px] font-bold',
  strongLabel: 'text-[12px] font-black',
  badge: 'text-[12px] font-bold',
  value: 'font-black tabular-nums',
  technicalCode: 'text-[12px] font-mono font-bold',
};
